
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author P A R S A
 */
public class IntercityDriver extends javax.swing.JFrame {

    private int DriverPk = 0;
    /**
     * Creates new form IntercityDriver
     */
    public IntercityDriver() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean validateFields(){
        if(!txtDriver.getText().equals("") && !txtSource.getText().equals("") && !txtDestination.getText().equals("") && !txtCar.getText().equals("")&& !txtPrice.getText().equals("")&& !txtPhone.getText().equals("")){
            return false;
        }
        else{
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtDriver = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtCar = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIntercity = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Intercity Driver");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Driver Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 214, -1, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Car");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 257, -1, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 308, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 349, -1, -1));

        btnAdd.setBackground(new java.awt.Color(204, 204, 255));
        btnAdd.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 410, 88, 39));

        btnCancel.setBackground(new java.awt.Color(204, 204, 255));
        btnCancel.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 90, 30));

        txtDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 116, 263, -1));

        txtSource.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceActionPerformed(evt);
            }
        });
        getContentPane().add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 164, 263, -1));

        txtDestination.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 210, 263, -1));

        txtCar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarActionPerformed(evt);
            }
        });
        getContentPane().add(txtCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 251, 263, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 296, 263, -1));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 343, 263, -1));

        tableIntercity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Driver's Name", "Source", "Destination", "Car", "Price", "Mobile Number"
            }
        ));
        tableIntercity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableIntercityMouseClicked(evt);
            }
        });
        tableIntercity.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableIntercityComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tableIntercity);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 101, 516, 350));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 410, -1, 39));

        btnReset.setBackground(new java.awt.Color(204, 204, 255));
        btnReset.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 410, 84, 39));

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 90, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/royalB.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void txtCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String drivername= txtDriver.getText();
        String source= txtSource.getText();
        String destination = txtDestination.getText();
        String car = txtCar.getText();
        String price= txtPrice.getText();
        String phone = txtPhone.getText();
      
        if(validateFields()){
            JOptionPane.showMessageDialog(null, "All fields are required");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into intercityDriver (drivername,source,destination,car,price,phoneNumber) values(?,?,?,?,?,?)");
                ps.setString(1,drivername);
                ps.setString(2,source);
                ps.setString(3,destination);
                ps.setString(4,car);
                ps.setString(5,price);
                ps.setString(6,phone);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Intercity Driver added successfully");
                setVisible(true);
                txtDriver.setText("");
                txtSource.setText("");
                txtDestination.setText("");
                txtCar.setText("");
        txtPrice.setText("");
        txtPhone.setText("");
                //new IntercityDriver().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IntercityDriver().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String drivername= txtDriver.getText();
        String source= txtSource.getText();
        String destination = txtDestination.getText();
        String car = txtCar.getText();
        String price= txtPrice.getText();
        String phone = txtPhone.getText();
      
        if(validateFields()){
            JOptionPane.showMessageDialog(null, "All fields are required");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("update intercityDriver set drivername=? ,source=? ,destination=? ,car=? ,price=? ,phoneNumber=? where driver_pk=?");
                ps.setString(1,drivername);
                ps.setString(2,source);
                ps.setString(3,destination);
                ps.setString(4,car);
                ps.setString(5,price);
                ps.setString(6,phone);
                ps.setInt(7,DriverPk);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Intercity Driver updated successfully");
                setVisible(true);
                txtDriver.setText("");
                txtSource.setText("");
                txtDestination.setText("");
                txtCar.setText("");
        txtPrice.setText("");
        txtPhone.setText("");
                //new IntercityDriver().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableIntercityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableIntercityMouseClicked
        // TODO add your handling code here:
        int index = tableIntercity.getSelectedRow();
        TableModel model = tableIntercity.getModel();
        String id = model.getValueAt(index, 0).toString();
        DriverPk = Integer.parseInt(id);
        
        String driver = model.getValueAt(index, 1).toString();
        txtDriver.setText(driver);
        
        String source = model.getValueAt(index, 2).toString();
        txtSource.setText(source);
        
        String destination = model.getValueAt(index, 3).toString();
        txtDestination.setText(destination);
        
        String car = model.getValueAt(index, 4).toString();
        txtCar.setText(car);
        
        String price = model.getValueAt(index, 5).toString();
        txtPrice.setText(price);
        
        String phone = model.getValueAt(index, 6).toString();
        txtPhone.setText(phone);
        
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tableIntercityMouseClicked

    private void tableIntercityComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableIntercityComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tableIntercityComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableIntercity.getModel();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from intercityDriver");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("driver_pk"),rs.getString("drivername"),rs.getString("source"),rs.getString("destination"),rs.getString("car"),rs.getString("price"),rs.getString("phoneNumber")});
            }
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                } 
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (DriverPk == 0) {
        JOptionPane.showMessageDialog(this, "Please select a driver to delete.");
        return;
    }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this driver?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("DELETE FROM intercityDriver WHERE driver_pk = ?");
                ps.setInt(1, DriverPk);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Intercity Driver deleted successfully.");

                // Reset fields
                txtDriver.setText("");
                txtSource.setText("");
                txtDestination.setText("");
                txtCar.setText("");
                txtPrice.setText("");
                txtPhone.setText("");

                // Refresh table
                DefaultTableModel model = (DefaultTableModel) tableIntercity.getModel();
                model.setRowCount(0); // clear existing rows
                formComponentShown(null); // reload data

                btnAdd.setEnabled(true);
                btnUpdate.setEnabled(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntercityDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntercityDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntercityDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntercityDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntercityDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableIntercity;
    private javax.swing.JTextField txtCar;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
