/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author P A R S A
 */

import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class TransportDriver extends javax.swing.JFrame {
    
    private int DriverPk = 0;

    /**
     * Creates new form TransportDriver
     */
    public TransportDriver() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean validateFields(){
        if(!txtDriver.getText().equals("") && !txtSource.getText().equals("") && !txtDestination.getText().equals("") && !txtTruck.getText().equals("")&& !txtPrice.getText().equals("")&& !txtPhone.getText().equals("")){
            return false;
        }
        else{
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtTruck = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransport = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transport Driver");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Driver Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Truck");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        txtDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 229, -1));

        txtSource.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceActionPerformed(evt);
            }
        });
        getContentPane().add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 229, -1));

        txtDestination.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 229, -1));

        txtTruck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTruckActionPerformed(evt);
            }
        });
        getContentPane().add(txtTruck, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 229, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 229, -1));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 229, -1));

        btnAdd.setBackground(new java.awt.Color(204, 204, 255));
        btnAdd.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 70, 33));

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 80, 33));

        btnReset.setBackground(new java.awt.Color(204, 204, 255));
        btnReset.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 70, 33));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, 33));

        tableTransport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Driver's Name", "Source", "Destination", "Truck", "Price", "Phone Number"
            }
        ));
        tableTransport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 540, 330));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 80, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/royalB.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void txtTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTruckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTruckActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String drivername= txtDriver.getText();
        String source= txtSource.getText();
        String destination = txtDestination.getText();
        String truck = txtTruck.getText();
        String price= txtPrice.getText();
        String phone = txtPhone.getText();

        if(validateFields()){
            JOptionPane.showMessageDialog(null, "All fields are required");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into transportDriver (drivername,source,destination,truck,price,phoneNumber) values(?,?,?,?,?,?)");
                ps.setString(1,drivername);
                ps.setString(2,source);
                ps.setString(3,destination);
                ps.setString(4,truck);
                ps.setString(5,price);
                ps.setString(6,phone);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Transport Driver added successfully");
                setVisible(true);
                txtDriver.setText("");
                txtSource.setText("");
                txtDestination.setText("");
                txtTruck.setText("");
        txtPrice.setText("");
        txtPhone.setText("");
        
               // new TransportDriver().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (DriverPk == 0) {
        JOptionPane.showMessageDialog(this, "Please select a driver to delete.");
        return;
    }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this driver?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("DELETE FROM transportDriver WHERE driver_pk = ?");
            ps.setInt(1, DriverPk);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Transport Driver deleted successfully.");

            // Reset fields
            txtDriver.setText("");
            txtSource.setText("");
            txtDestination.setText("");
            txtTruck.setText("");
            txtPrice.setText("");
            txtPhone.setText("");
            
            // Refresh table
            DefaultTableModel model = (DefaultTableModel) tableTransport.getModel();
            model.setRowCount(0); // clear existing rows
            formComponentShown(null); // reload data

            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TransportDriver().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String drivername= txtDriver.getText();
        String source= txtSource.getText();
        String destination = txtDestination.getText();
        String truck = txtTruck.getText();
        String price= txtPrice.getText();
        String phone = txtPhone.getText();

        if(validateFields()){
            JOptionPane.showMessageDialog(null, "All fields are required");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("update transportDriver set drivername=? ,source=? ,destination=? ,truck=? ,price=? ,phoneNumber=? where driver_pk=?");
                ps.setString(1,drivername);
                ps.setString(2,source);
                ps.setString(3,destination);
                ps.setString(4,truck);
                ps.setString(5,price);
                ps.setString(6,phone);
                ps.setInt(7,DriverPk);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Transport Driver updated successfully");
                setVisible(true);
                txtDriver.setText("");
                txtSource.setText("");
                txtDestination.setText("");
                txtTruck.setText("");
                txtPrice.setText("");
                txtPhone.setText("");
                //new IntercityDriver().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableTransportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransportMouseClicked
        // TODO add your handling code here:
        int index = tableTransport.getSelectedRow();
        TableModel model = tableTransport.getModel();
        String id = model.getValueAt(index, 0).toString();
        DriverPk = Integer.parseInt(id);
        
        String driver = model.getValueAt(index, 1).toString();
        txtDriver.setText(driver);
        
        String source = model.getValueAt(index, 2).toString();
        txtSource.setText(source);
        
        String destination = model.getValueAt(index, 3).toString();
        txtDestination.setText(destination);
        
        String car = model.getValueAt(index, 4).toString();
        txtTruck.setText(car);
        
        String price = model.getValueAt(index, 5).toString();
        txtPrice.setText(price);
        
        String phone = model.getValueAt(index, 6).toString();
        txtPhone.setText(phone);
        
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tableTransportMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableTransport.getModel();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from transportDriver");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("driver_pk"),rs.getString("drivername"),rs.getString("source"),rs.getString("destination"),rs.getString("truck"),rs.getString("price"),rs.getString("phoneNumber")});
            }
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                } 
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransport;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTruck;
    // End of variables declaration//GEN-END:variables
}
